Day3
salixa/SNSC3-Translation pull request #3
Opened 2018-03-31 11:01 UTC by fmazu

I translated the remaining untranslated partner dialogue on Day 3.
I translated the dialogue for all partners but I’m only playing Rufeel so far. I checked other dialogues to match the personality of each partner in the translation but let me know if the translation feels off.

2018-04-03 13:22 UTC, salixa requested changes

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +	<ascii>
For Run-Dor's dialogue, the convention is to capitalize the first letter of every word => "Her Strength May Be Unknown"

"Strength" is misspelled here
Sentence would flow better if "but" was moved to the second line

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Let's take her to Marnail Station.<end_line>
Marnail => Marneil

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Well, if that's how you fell<end_line>
fell => feel
"us" is not necessary here, it's kind of redundant given that "our" implies both ownership of something (the money) and oneself plus another.

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Does it hurt?<end_line>
Repeat dialogue feels stiff even if it is true to the original text. Could either change above "Ah, it hurts!" to something like "Ah, ouch!" or "Does it hurt?/Are you ok?" to another expression of concern.

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		It's as if you're healed<end_line>
For Run-Dor's dialogue, the convention is to capitalize the first letter of every word.

This line (and Rufeels) translated literally doesn't flow very well in english. As long as the line gets the point across that Partner is calling out Tier's fake illness, we don't need to stick to the JP so closely (that applies for everything really). "You've certainly recovered quickly.", "It's as if you've recovered already", etc. etc.

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		all better<three_dots>?
Missing <end_line> tag, see above comment in Run-Dor's version

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		but we have to find her.<three_dots><end_line>
"her" -> "Tier". Since this is help dialogue that can be referenced at any time it should be more explicit. If for example the player stopped playing the game for a while, they may not remember who "her" refers to.

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		at your age<end_line>
Words could be rearranged to make better use of space. When you look at it in the text box this will look like:

==============

=====

=============

Preferably, either all lines will be approximately the same length, or the last line will be the shortest.

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +			Alright!I'll do my best!<end_line>
Space between "Alright!" and "I'll"

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +	<ascii>
"Good grief" doesn't fit Killfith's personality. He's more of a dismissive, tsundere edgelord type who hates being tied down to the protagonist. As such more dismissive expressions of exasperation such as "Ugh" or sighs, or light insults towards the player will both fit for lines like these.

"involded" => "involved"

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +	<ascii>
Remove "." at end of "Sorry"

Add comma at the end of 671

The player here is asking Killfith to deal with it in a nice way. "so let's give it our best?" => "so bear with it, okay?"

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Lady Murno is awaiting for us,<end_line>
"awaiting" usage is improper, one way to use it would be "awaiting our return", or could be changed to "waiting" instead.

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +	<ascii>
Works, but could be condensed and edited to show off a bit more of Rufeel's personality. Personally I would translate this as:

Oh come now,<end_line>
still feeling down<three_dots>?<end_line>
Here, let's hold hands, and then<three_dots><end_line>

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Felling better?<end_line>
"Felling" => "Feeling"

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Thank you!<end_line>
"Thank you" => "Thanks"

Player generally speaks casually

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		I'll you everything when the time is right<three_dots><end_line>
Missing "tell", could also be shortened to simply "When the time is right"

2018-04-03 13:22 UTC, salixa commented on Day 03/24382732_1740d0c.xml
> +		Yes, when the time comes<end_line>
Add comma or period at the end of first sentence

2018-11-10 10:42 UTC, fmazu commented
Hi, sorry for the long (really long) time to fix this PR, but I just did the changes and was looking into the conflicting parts...
It seems you've already finished this yourself correct? @salixa 
If that's the case we can close the PR.

2018-11-25 19:26 UTC, salixa commented
Confirmed most of it was already merged by myself.

2018-11-25 19:26 UTC, closed without merging